version: '3.7'
services:
  jira-app:
    build: .
    command: python ./jira_reports.py
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env

  filebeat:
    user: "filebeat"
    image: docker.elastic.co/beats/filebeat:8.8.0
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/app/logs
    depends_on:
      - jira-app
