## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml
#

name: filebeat

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /app/logs/*.log


# Commenting out Elasticsearch output
# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]
#   username: filebeat_internal
#   password: ${FILEBEAT_INTERNAL_PASSWORD}

# Adding Logstash output
output.logstash:
  hosts: ["43.205.192.21:9600"]

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
#

http:
  enabled: true
  host: 0.0.0.0
